# examples/notify_on_matches_helpers.yaml
alias: Notify on local CAP matches (Helpers)
mode: single
trigger:
  - platform: time_pattern
    minutes: "/15"
action:
  - service: cap_alerts.find_matches
    data:
      lat: "{{ states('input_number.watch_lat_1') }}"
      lon: "{{ states('input_number.watch_lon_1') }}"
      radius_km: 25
  - wait_for_trigger:
      - platform: event
        event_type: cap_alerts.matches
    timeout: "00:00:10"
  - choose:
      - conditions: "{{ trigger.event.data.count | int(0) > 0 }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "CAP Matches near Watchpoint 1"
              message: >-
                {{ trigger.event.data.count }} match(es).
